updated according to requested changes
rahulrk-dev/snips pull request #64
Opened 2023-10-11 09:08 UTC by sparshmanni

2023-10-11 15:09 UTC, rahulrk-dev requested changes

2023-10-11 15:09 UTC, rahulrk-dev commented on src/count_occurrence.md
> +int countOccurrences(const std::vector<int>& arr, int valueToCount) {
See if u can do it without including vector lib

2023-10-11 16:43 UTC, rahulrk-dev commented
Rename file in camel case (countOccurrence.md)

2023-10-11 18:51 UTC, sparshmanni commented
> Rename file in camel case (countOccurrence.md)   -DONE

> Removed vector from C++ snippet  -DONE

2023-10-11 19:35 UTC, rahulrk-dev commented on src/countOccurrence.md
> +int countOccurrences(int arr[], int size, int valueToCount) {
Why passing 3 arguments here, it's changing the snip structure

2023-10-11 19:37 UTC, rahulrk-dev commented on src/countOccurrence.md
> +int countOccurrences(int arr[], int size, int valueToCount) {
If it's getting too complex, you can remove snip for snip for C++

2023-10-12 10:51 UTC, sparshmanni commented on src/countOccurrence.md
Removed third para from function for C++

2023-10-12 19:07 UTC, rahulrk-dev approved these changes
Thanks @sparshmanni, merging

2023-10-12 19:09 UTC, merged