Update csvStringToObject.md
rahulrk-dev/snips pull request #69
Opened 2023-10-14 11:38 UTC by sparshmanni

Added Snip in Python lang to csvStringToObject.md

2023-10-14 18:36 UTC, rahulrk-dev requested changes

2023-10-14 18:36 UTC, rahulrk-dev commented on src/csvStringToObject.md
> +def csv_to_json(data, delimiter=','):
The function name should match the one in the example

2023-10-14 18:36 UTC, rahulrk-dev commented on src/csvStringToObject.md
> +    csv_data = io.StringIO(data)
Do not use any external library, because if someone copies this function it might not work for them because of dependency

2023-10-14 18:37 UTC, rahulrk-dev commented on src/csvStringToObject.md
> +    csv_data = io.StringIO(data)
See if you can do it without using any lib so the function can be used easily

2023-10-27 20:05 UTC, rahulrk-dev commented
Hey @sparshmanni, are you working on this?

2023-10-31 12:13 UTC, sparshmanni commented
> Hey @sparshmanni, are you working on this?

Sorry for not reverting, as I was not active due to some reasons.

2023-10-31 13:26 UTC, rahulrk-dev approved these changes
Thanks @sparshmanni, merging

2023-10-31 13:28 UTC, rahulrk-dev commented
> > Hey @sparshmanni, are you working on this?
> 
> Sorry for not reverting, as I was not active due to some reasons.

Not a problem mate, was just checking

2023-10-31 13:28 UTC, merged