Create ByteSizeOfString.md
rahulrk-dev/snips pull request #72
Opened 2023-10-28 17:58 UTC by shafa-shabudeen

Created a program that demonstrates how to calculate the size of a string in bytes. It takes a user-defined string, converts it to bytes using the default character encoding (usually UTF-8), and then returns the size of the string in bytes

2023-10-30 18:38 UTC, rahulrk-dev commented on src/ByteSizeOfString.md
> +        System.out.println("Size of the string in bytes: " + sizeInBytes);
Do not just print the result, return them for all 3 languages

2023-10-30 18:39 UTC, rahulrk-dev requested changes
Use camel casing for file name

2023-11-01 10:55 UTC, shafa-shabudeen commented
I made the changes and rename the file also.

2023-11-01 13:45 UTC, rahulrk-dev approved these changes
Thanks @shafa-shabudeen, merging

2023-11-01 13:46 UTC, merged

2023-11-01 17:27 UTC, shafa-shabudeen commented
Thank you